### ISSUE TITLE
Loot Crates Auto Generation

### ISSUE THREAD

**Issue by TheCiROMG** [PeriodicSeizures/LootCrates#1]
As the title says, I would like you to add the option that they are generated automatically in the world, and if a timer is possible, it would be much better, the lootcrate chests would be auto generated every 30 minutes, and my players will have the opportunity to have very good items

**Comment by crazicrafter1** [comment]
I just updated LootcratesExtended which already had this feature, it previously would be incompatible with the latest lootcrates (3.0.1), https://www.spigotmc.org/resources/lootcrates-extended.72032/
