### ISSUE TITLE
Crate editor doesn't save playerhead data

### ISSUE THREAD

**Issue by michaelabrannen** [PeriodicSeizures/LootCrates#2]
Version 3.3.10

The in game editor doesn't save the playerhead's skull and it turns into a steve head.

![image](https://user-images.githubusercontent.com/84884414/156097139-9da4147d-1147-480a-9e2a-e85b81920d2f.png)
After hitting back
![image](https://user-images.githubusercontent.com/84884414/156097181-ace3098e-68f2-4613-ae5a-898b09b90153.png)

**Comment by crazicrafter1** [comment]
I think this is just a visual issue in the editor for now. Are you able to confirm that the crate itself when given with **/crates crate** is not a textured head?

**Comment by crazicrafter1** [comment]
So I thought I had fixed this issue, but it wasn't. It's fixed now.
