### ISSUE TITLE
Loot NBT Doesn't save on restart

### ISSUE THREAD

**Issue by michaelabrannen** [PeriodicSeizures/LootCrates#3]
If there is custom NBT tags on a item in a loot table, it won't get saved when the config is reloaded. It will however save things like name and lore nbt correctly.

Steps to reproduce:

1. Get an item with custom NBT tags (not normal tags like name/lore). 
     1a.  ex of an item I use on my server: /give @p amethyst_shard{shoppingTeleport:1} 1
2. Add it to a loot table through crates editor.
3.  /crates save
4. Loot crates work appropriately at this point.
5. /crates reload (or a server restart, which is the main reason this is a problem)
6. Item will not save that custom nbt data. Crates no longer work as expected when you receive an item with the custom nbt.

The custom nbt is useful in my server because it's how I can write some custom logic to normal items. Without the nbt the items do nothing.

**Comment by crazicrafter1** [comment]
Fixed in release 3.3.13
