### ISSUE TITLE
Command Loot

### ISSUE THREAD

**Issue by FeuSalamander** [PeriodicSeizures/LootCrates#5]
Is it possible for a player to drop a loot that executes a command instead of giving him the item ?

**Comment by crazicrafter1** [comment]
There is a Command Loot that likely does what you are referring to:
![image](https://github.com/PeriodicSeizures/Lootcrates/assets/47781580/8c081635-bae5-4807-9901-f13dd4db4f71)
Its located in the loot add menu (`Loot` -> `click a lootset` -> `Add item`).

It runs as op and supports PlaceholderAPI player macros.

**Comment by FeuSalamander** [comment]
Ohh ok, I am dumb, Thank you for your fast reply and your good plugin 😃
